### ISSUE TITLE
Question about the calibration module in utils_3d_reconstruct.py

### ISSUE THREAD

**Issue by chaytonmin** [ntu-rris/google-mediapipe#1]
Can the calibration module in utils_3d_reconstruct.py be used for calibrating  more than two cameras ( i.e., not stereo but MVS)?

**Comment by guanming001** [comment]
Hi @chaytonmin the calibration module in [utils_3d_reconstruct.py](code/utils_3d_reconstruct.py) cannot be used to calibrate more than two cameras.

For camera calibration of multi-view setup, you may want to refer to another [repo](https://github.com/gmntu/mirror) in these two sample codes:  [02_calib_extrin_video.py](https://github.com/gmntu/mirror/blob/master/code/02_calib_extrin_video.py) or [02_calib_extrin.py](https://github.com/gmntu/mirror/blob/master/code/02_calib_extrin.py), they perform extrinsic calibration of multiple cameras (2 or more) using a [bundle-adjustment like method](https://ieeexplore.ieee.org/document/6696517)

**Comment by chaytonmin** [comment]
> Hi @chaytonmin the calibration module in [utils_3d_reconstruct.py](code/utils_3d_reconstruct.py) cannot be used to calibrate more than two cameras.
> 
> For camera calibration of multi-view setup, you may want to refer to another [repo](https://github.com/gmntu/mirror) in these two sample codes: [02_calib_extrin_video.py](https://github.com/gmntu/mirror/blob/master/code/02_calib_extrin_video.py) or [02_calib_extrin.py](https://github.com/gmntu/mirror/blob/master/code/02_calib_extrin.py), they perform extrinsic calibration of multiple cameras (2 or more) using a [bundle-adjustment like method](https://ieeexplore.ieee.org/document/6696517)

Thanks a lot. I will try it.
