### ISSUE TITLE
Behaviour of 08_skeleton_3D

### ISSUE THREAD

**Issue by gb2111** [ntu-rris/google-mediapipe#2]
Hi.
I'd like to ask how this demo is supposed to work. I can see in Open3D window the same thing as in "img 2D".
Thanks

**Comment by guanming001** [comment]
Hi

The Open3D window allows you to view the **skeleton in 3D** and also the 2D image projected to a 3D plane.
You will get the below view if you use the mouse to scroll/adjust the viewpoint in Open3D window:
![ScreenCapture_2021-07-16-12-51-40](https://user-images.githubusercontent.com/38412160/125893839-149a1526-b459-4618-88b1-6f2aa2315353.png)

**Comment by gb2111** [comment]
Thanks.
