### ISSUE TITLE
Demo of body 3d pose in space

### ISSUE THREAD

**Issue by gb2111** [ntu-rris/google-mediapipe#3]
Hello.
I was looking at 05_wrist_rom where I can see hand in 3d being properly positioned in all 3 axis, that is left, right and depth with default parameters.
In new mediapipe there is also position in meters but origin is in hips. Could you consider making demo of body pose but located in space same as you have now hand? 
Thank you for great examples.

**Comment by guanming001** [comment]
Hi @gb2111 thank you for your interest in this project.

I only tried to convert the hand joint to 3D space with reference to camera coordinate by making some **simplified assumptions** such as the distance between wrist to index finger MCP  is around 8 cm and the distance from the hand to camera is around 0.6 m (details can be found in the [convert_joint_to_camera_coor](https://github.com/ntu-rris/google-mediapipe/blob/329d2345cf3be4e5c821195b898c5bbc1ee2e9a0/code/utils_mediapipe.py#L295) function).

However, when I tried to apply similar assumptions to the human body, the results are not as good, perhaps due to the greater diversity in human body dimensions and the distance from the body to single camera view is much harder to estimate due to depth ambiguity.

**Comment by gb2111** [comment]
But I have seen that you have had some kind of depth estimation and you must have done some updates. 
On readme of this repo, we have 08_skeleton_3D gif that put a skeleton in some perspective. While now when I run the demo it is at the source of the camera. I think 01_video before was also in some perspective and now middle of hips is simple in camera source.

Second question. Do you somehow normalize skeleton that it hold always same size?
Thanks.

**Comment by guanming001** [comment]
Hi @gb2111 

I made some update to try to estimate the body joint in camera coordinate (details can be found in [convert_body_joint_to_camera_coor](https://github.com/ntu-rris/google-mediapipe/blob/3e76af93a69a2b2baa5bbc624f59f765066a332e/code/utils_mediapipe.py#L446) function).

Below are the result when tested on the video taken from [The Greatest Showman](https://www.youtube.com/watch?v=qlPRDVqYO74) inspired by the work of [VIBE: Video Inference for Human Body Pose and Shape Estimation [CVPR-2020]](https://github.com/mkocabas/VIBE). 
When the person is closer to the camera, his 3D joints also appears closer, but take note that the it is still not very stable and accurate as the actual camera intrinsics are unknown and it only uses 4 keypoints to estimate the 3D pose, if you have any suggestions/improvements feel free to make a pull request.
![ezgif com-gif-maker](https://user-images.githubusercontent.com/38412160/126075240-55836d11-0c8a-4fde-a39f-4ea2331eae05.gif)

P.S. For the 08_skeleton_3D gif I think the hip was hardcoded and fixed at some distance in front of the camera

**Comment by gb2111** [comment]
Yes. actually I have idea :)
Not sure with each frame we have situation where we have
1. 3d model (fixed size, not scaled)
2. projection of the model to image.
This is perfect input to SolvePNP from OpenCV. What do you think ?

Also can you tell if you scale or not the model? If not how you make it fixed size?

Greg

**Comment by guanming001** [comment]
I have added two options to the [convert_body_joint_to_camera_coor](https://github.com/ntu-rris/google-mediapipe/blob/433a230c1b960869b74ca0e6007a77b0d007b22d/code/utils_mediapipe.py#L446) function you can give it a try:
* **scale_body** to try to fix the body dimension (e.g. hip width, arm length, leg length)
* **use_solvepnp**  but sometimes the depth of the joint may be estimated wrongly (i.e. translation in z direction is negative)

**Comment by gb2111** [comment]
Thank  you for adding this! I'd say they both work very well.  I can see you are using all 33 landmarks for SolvePNP. I am surprised it works :) Can't tell which one works better. 
I am not sure why you added **scale_body** cause you already take it from **pose_world_landmarks** which are already unified?

**Comment by guanming001** [comment]
The scale_body option was just to test if a fixed sized body model works, but anyway the latest version of MediaPipe 0.8.6 already offers quite a useful estimate of real-world 3D body joint so the scale_body option may not be necessary.

**Comment by gb2111** [comment]
Thanks for clarification 
Honestly, I think it works quite well. 
Again I appreciate you made these changes.

**Comment by gb2111** [comment]
@guanming001 
I wonder if you could do one more try. Namely to use same 4 points to SolvePNP. You need to have global variables for rvec and tvec and always pass them to function as argument and read as result.
I am using something similar in C# and it allows to use 4 points
```
(_, rotation_vector, translation_vector) = cv2.solvePnP(
            points_model,
            image_points,
            self.camera_matrix,
            self.dist_coeefs,
            rvec=self.r_vec,
            tvec=self.t_vec,
            useExtrinsicGuess=True)
```

**Comment by gb2111** [comment]
Ok. I improved my python skills and added class variable for rotation and translation and use it as described above. I initialize the translation vector as [0,0,1] so the estimated pose is in a good location always. Now I can use SolvePnP either with 4 or with all landmarks.

When using 4 points need to remove multiplication by ```rmat = cv2.Rodrigues(rvec)[0]``` what doesn't seem to be required as we have very good rotation from mediapipe and here we need the only position. So in the end I removed it entirely.

So now we have in theory 3 methods. I cannot tell which one is better. Ideally would be good to compare one by one same video and have always the same view of camera. If you have a code snippet on how to initialize the camera with a view pls share it.

Thanks again for adding pnp to your repo!

**Comment by guanming001** [comment]
Thank you for your suggestions!

By initializing the rvec, tvec, and enable useExtrinsicGuess, it allows solvepnp to use 4 landmarks and the issue of negative z translation is gone.

You can initialize the camera view, by simply [pressing the key 'r' ](https://github.com/ntu-rris/google-mediapipe/blob/b55fd259ef766da3b3aab67f9cbed222c8a9df91/code/08_skeleton_3D.py#L107) which will reset to default camera view. 

If you want a different view you can change the value of [identity matrix](https://github.com/ntu-rris/google-mediapipe/blob/b55fd259ef766da3b3aab67f9cbed222c8a9df91/code/utils_display.py#L942) in `self.pinhole.extrinsic`.

Or you can also replace the [reset_view](https://github.com/ntu-rris/google-mediapipe/blob/b55fd259ef766da3b3aab67f9cbed222c8a9df91/code/utils_display.py#L949) function with the below code:
```python
def reset_view(self):
    # Set camera view
    ctr = self.vis.get_view_control()
    ctr.set_up([0,-1,0]) # Set up as -y axis
    ctr.set_front([1,-1,-1])
    ctr.set_lookat([0,0,3])
    ctr.set_zoom(0.5)
```

**Comment by gb2111** [comment]
I will give it a try. 

Do you know if there is way to overlay 3d skeleton only with opencv in way like you have initially with open3d ?
Thank you.
