### ISSUE TITLE
Calibration of stereo camera based on world landmarks

### ISSUE THREAD

**Issue by gb2111** [ntu-rris/google-mediapipe#5]
Hi,
I have seen you have also a module based on stereo camera. I wonder if you'd be interested in idea of calculating camera calibration (basically only relative position) using just a pose from 2 cameras?
The idea is that you capture points in 2d and also have a 3d model from world landmarks. We assume that there is one valid model for example from 1st camera. If we apply SolvePNP with first model to 2d points of first and second camera and negate (I think) the 3d coordinates we can get actual pose of the both cameras. This method most likely will be far in precision from chessboard but if we capture few samples and take only most important joints then it might lead to good enough estimate to use it with mediapipe.
I am just writing about this feature in case you are interested and find it applicable to your solution. 
If that is not applicable to your project our you simply doesn't have time then sorry and I shall close this issue :)
Thanks,
Greg

**Comment by zbzzz** [comment]
Hello, may I ask if you have achieved that? Recently, I have had a similar concern as well.
